### ISSUE TITLE
XPbar doesn't work on mobile

### ISSUE THREAD

**Issue by SuryaniD** [SuryaniD/ProefProeve2#1]
The XPbar doesn't work on Android(Samsung A50)
The bar needs to be made bigger too.

**Comment by toonschaap** [comment]
probably a problem with the if statement

**Comment by toonschaap** [comment]
UPDATE: if statement changed, now shows "error CS1056: Unexpected character '?'" after switching platform for building

**Comment by toonschaap** [comment]
fixed with latest push
